# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30, verbose_name='Bus Name')),
                ('status', models.CharField(choices=[('REG', 'Registered'), ('OPN', 'Open/Not Registered')], default='OPN', max_length=3, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Coord_Reporter',
            fields=[
                ('reporter_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('acceptance_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coordinates Reporters',
            },
        ),
        migrations.CreateModel(
            name='Coord_Reporter_Request',
            fields=[
                ('request_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('request_created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Request created on')),
                ('respond_date_time', models.DateTimeField(null=True)),
                ('respond_status', models.CharField(choices=[('NVR', 'Not Verified'), ('DND', 'Denied')], default='NVR', max_length=3)),
                ('requestedfor_bus_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Admin.Bus', verbose_name='Requesting for bus')),
            ],
            options={
                'verbose_name': 'Coordinates Reporting Requests',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Route ID')),
                ('route_name', models.CharField(max_length=50, unique=True, verbose_name='Route Name')),
            ],
            options={
                'verbose_name': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Stop ID')),
                ('stop_name', models.CharField(max_length=50, unique=True, verbose_name='Stop Name')),
            ],
            options={
                'verbose_name': 'Stops',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='User Name')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('is_superuser', models.BooleanField(default=False, editable=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=148, unique=True, verbose_name='Email')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('cell_number', models.CharField(max_length=13, verbose_name='Cell Number')),
                ('last_login', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Users',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(to='App_Admin.Stop', verbose_name='Have stops'),
        ),
        migrations.AddField(
            model_name='coord_reporter_request',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Admin.User', verbose_name='Requested by'),
        ),
        migrations.AddField(
            model_name='coord_reporter',
            name='accepted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_by', to='App_Admin.User'),
        ),
        migrations.AddField(
            model_name='coord_reporter',
            name='allocated_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Admin.Bus'),
        ),
        migrations.AddField(
            model_name='coord_reporter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Admin.User', verbose_name='Reporter'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Admin.Route', verbose_name='Route Number'),
        ),
    ]
