# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0002_auto_20160502_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_admin_origin_stop_related', to='App_Admin.Stop', verbose_name='Origin Stop'),
            preserve_default=False,
        ),
    ]
