# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0002_auto_20160425_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord_reporter',
            name='allocated_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Admin.Bus'),
        ),
        migrations.AlterField(
            model_name='coord_reporter',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Admin.User'),
        ),
        migrations.AlterField(
            model_name='coord_reporter_request',
            name='respond_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coord_reporter_request',
            name='respond_status',
            field=models.CharField(choices=[('NVR', 'Not Verified'), ('DND', 'Denied')], default='NVR', max_length=3),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Route Name'),
        ),
    ]
