# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0003_auto_20160426_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord_reporter_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Admin.User', unique=True),
        ),
    ]
